### ISSUE TITLE
Results of `MATCH` .. with `OPTIONAL MATCH` are not rendered

### ISSUE THREAD

**Issue by bigluck** [kuzudb/explorer#100]
Something odd seems to happen when using `OPTIONAL MATCH`.

I'm using the latest version of the explorer (0.3.2) via docker.

This query produces a graph:
```cypher
MATCH
    (n:PhyTask)<-[r:UsedByPPTask]-(m:Fn),
    (a:Artifact)-[r2:IsInputArtifactOf]-(m)
RETURN *
```

<img width="1552" alt="Screenshot 2024-03-14 at 17 53 31" src="https://github.com/kuzudb/explorer/assets/1511095/3055536d-c7d0-45c2-97b0-5b99a8d7520d">

But when using `OPTIONAL MATCH`:
```cypher
MATCH
    (n:PhyTask)<-[r:UsedByPPTask]-(m:Fn)
OPTIONAL MATCH
    (a:Artifact)-[r2:IsInputArtifactOf]-(m)
RETURN *
```

the explorer fails with this error on the console:
```
[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 't.table')
	encodeNodeId (index.e594caef.js:1:415135)
	h (index.e594caef.js:1:415341)
	(anonymous function) (index.e594caef.js:1:416495)
	forEach
	extractGraphFromQueryResult (index.e594caef.js:1:416429)
	drawGraph (index.e594caef.js:1:412494)
	(anonymous function) (index.e594caef.js:1:429219)
```
<img width="1552" alt="Screenshot 2024-03-14 at 17 54 20" src="https://github.com/kuzudb/explorer/assets/1511095/d1fb738b-1ebc-41cd-9671-66d09e45c011">

even if the cypher endpoint responded with some rows (and their content is visible on the table view):
<img width="1552" alt="Screenshot 2024-03-14 at 17 56 01" src="https://github.com/kuzudb/explorer/assets/1511095/b6fc7f1d-3b2c-4bcb-b40b-bf02d4e73c70">

**Comment by mewim** [comment]
This looks like a bug. I'll look into it. Would it be possible for you to share the database with me?

**Comment by bigluck** [comment]
Of course, ping me on discord
