### ISSUE TITLE
Aesthetics: Make node border colors and arrowheads consistent with schema view

### ISSUE THREAD

**Issue by prrao87** [kuzudb/explorer#109]
#101 made the schema visualization really nice-looking. For the query browser, it would be nice to add a similar enhancement.

The following shows how it currently looks when returning a query result:

![image](https://github.com/kuzudb/explorer/assets/35005448/8138bdc2-9eae-48ff-a2fe-8ba401368e1d)

The schema view looks like this:

![image](https://github.com/kuzudb/explorer/assets/35005448/fe886769-8e05-4e19-80fa-40b023451c1d)

### Changes

- [x] We should color the nodes for query results the same way as we do for the schema view: the border color should be a darker version of the node's background color. This would make it much nicer aesthetically and more similar to other graph visualization tools.
- [x] We should also make the arrowhead shapes in the query result similar to the schema view - having a filled triangle as the arrowhead (as we do in the schema view) looks better for a relationship visualization in a graph.

**Comment by mewim** [comment]
1 is handled.
I checked 2 and it seems I did not do anything special to configure the edge style - it is simply an effect of line width. I will see if there is any alternative solution to override the arrow style.

**Comment by prrao87** [comment]
We could just increase the line width like we do in the schema. Same setting, same effect :)

**Comment by prrao87** [comment]
Seems like the arrowheads can be customized by using `G6.Arrow.triangle` per [the docs](https://antv-g6.gitee.io/en/docs/manual/middle/elements/edges/arrow)

**Comment by mewim** [comment]
<img width="2032" alt="Screenshot 2024-03-20 at 8 11 27 PM" src="https://github.com/kuzudb/explorer/assets/14037726/3ba6408b-4d32-4b21-8caf-5d426e518f06">
