### ISSUE TITLE
Schema view inconsistency when user modifies the schema via shell

### ISSUE THREAD

**Issue by mewim** [kuzudb/explorer#11]
If the user issues DDLs from the shell to update the schema, the schema view will not reflect up-to-data information unless the user refreshes the entire page. There should be a way to detect schema changes via shell DDL and perform the refresh automatically.

**Comment by Riolku** [comment]
How expensive would it be to reload the schema every time a shell command is issued? Seems like a very easy way to do it.

**Comment by mewim** [comment]
It is not expensive, but I think a better way is to return an additional flag from the backend API and refresh when necessary.

**Comment by Riolku** [comment]
Like you want kuzu itself to return such a flag?

**Comment by mewim** [comment]
I think it can be handled at the Node.js level. No need for the database to handle it.

**Comment by Riolku** [comment]
I feel like kuzu should not be forced to handle this if at all possible
