### ISSUE TITLE
Improve error message readability

### ISSUE THREAD

**Issue by bigluck** [kuzudb/explorer#114]
The explorer does not honor the new lines on error messages.

In my case the API endpoint returned this response error:

```json
{
    "error": "Parser exception: Invalid input <MATCH\n    (task:PhyTask)-[r1:HasPhyTaskImplementation]->(task_impl:PhyTaskCode),\n    (docker_task:PhyTask)-[r2:PhyTaskFollowBy]->(task),\n    (docker_task)-[r3:HasPhyTaskImplementation]->(docker_task_impl:PhyTaskDockerImagePull)\nWHERE\n    task_impl.pip_dependencies IS NOT NULL\nUNWIND task_impl.pip_dependencies\nRETURN>: expected rule oC_SingleQuery (line: 8, offset: 0)\n\"RETURN *\"\n ^^^^^^"
}
```

But the explorer makes it harder to read:

<img width="863" alt="Screenshot 2024-03-19 at 09 40 41" src="https://github.com/kuzudb/explorer/assets/1511095/2e08d1ac-e4e5-4510-9e31-2f69290c59be">

**Comment by mewim** [comment]
<img width="1896" alt="Screenshot 2024-03-20 at 6 50 46 PM" src="https://github.com/kuzudb/explorer/assets/14037726/04792847-e6d5-4421-965d-411aa8251206">

I have changed the rendering of the error messages using the `<pre>` element to preserve the line breaks and defaults to monospace font. This should hopefully improve the readability.
