### ISSUE TITLE
[feature request] Override default settings via ENVs

### ISSUE THREAD

**Issue by bigluck** [kuzudb/explorer#124]
I'd love it if the default options could be overridden using environment variables.

In my case, I need to re-start the docker container every time I change my graph, but by restarting it I lose all my settings like:
- Nodes Size
- Nodes Caption
- Number of rows per page
- GPT Api key & model

I know that certain configurations can be set for each node type/label, but currently, I just want to override the default settings using something like:
- `KUZU_EXPLORER_DEFAULT_NODE_SIZE=100`
- `KUZU_EXPLORER_DEFAULT_NODE_CAPTIONSE=TABLE_LABEL`
- `KUZU_EXPLORER_NUMBER_OF_ROWS_PER_PAGE=50`

Thanks! :)

**Comment by bigluck** [comment]
For reference, this is the workaround I'm using now :)

```javascript
settings = document.querySelectorAll('div.modal-body table')[0]
settings.querySelectorAll('tr input[type=number]').forEach((a) => { a.value = 100;  a.dispatchEvent(new Event('input', { bubbles: true, cancelable: true })); });
settings.querySelectorAll('tr select').forEach((a) => { a.selectedIndex = 0; a.dispatchEvent(new Event('change', { bubbles: true, cancelable: true })); });
```

**Comment by mewim** [comment]
We have persisted the settings in a local SQLite3 database (other than the GPT token) stored under the same directory as the kuzu database you open if you open it in `READ_WRITE` mode. Is this not working for you? If not, there might be a bug.

**Comment by bigluck** [comment]
Oh I see. no in my case unfortunately it does not work, not for a bug but because I always recreate the DB from the scratch and the old folder is automatically deleted :(

**Comment by mewim** [comment]
OK. In this case, I think I'll implement two-levels of setting storage. I would also store the settings in browser `localStorage` but give a preference to the SQLite database. I'll let you know when this is done.
