### ISSUE TITLE
Add an empty query cell above the first one

### ISSUE THREAD

**Issue by prrao87** [kuzudb/explorer#127]
When the user deletes all empty query cells using the ❌ button, there's no way to add a new cell other than refreshing the page (this might cause them to lose any existing queries). I think it makes sense to add a small box at the top of the page called "Insert new cell" similar to how it would be in a Jupyter notebook or the Neo4j query editor. Something like the following:

<img width="785" alt="image" src="https://github.com/kuzudb/explorer/assets/35005448/6f129d08-843e-4d5b-8c53-cab60dd2c0c8">

**Comment by mewim** [comment]
The design was that there should always be at least one cell.

https://github.com/kuzudb/explorer/blob/f988aff1c7fcb104654bec69f896f64ae2cbbbf5/src/components/ShellView/ShellMainView.vue#L83

If there is 0 cell, an empty cell will be created automatically.
