### ISSUE TITLE
Allow query cell to be resized to show long queries

### ISSUE THREAD

**Issue by prrao87** [kuzudb/explorer#128]
For certain queries that are reasonably long, the only way to see the entire query is to scroll up and down. It would be nice to allow the user to be able to resize the query cell so that the entire query is visible at once.

Example long query that's cut off:
<img width="835" alt="image" src="https://github.com/kuzudb/explorer/assets/35005448/246372e8-39e9-447c-9a90-ef5935262606">

**Comment by mewim** [comment]
Added resize handle:

<img width="2032" alt="Screenshot 2024-04-01 at 7 16 44 PM" src="https://github.com/kuzudb/explorer/assets/14037726/3392b106-fb98-4473-a95c-722163b38e4e">
