### ISSUE TITLE
Error: std::bad_alloc

### ISSUE THREAD

**Issue by fils** [kuzudb/explorer#137]
Curious if there is a known reason I might be getting the following errors trying on on Fedora and Ubuntu.

Has this been seen before, a quick search of issues didn't seem to show any.

Thanks

podman on Fedora
```bash
(base) ~/src/Projects/NIAID/domainAssessment/sof git:[master]
podman run --privileged --group-add keep-groups -e GRANT_SUDO=yes --user root -p 8000:8000  -e MODE=READ_ONLY -v /home/fils/src/Projects/NIAID/domainAssessment/sof/kuzu:/database --rm kuzudb/explorer:latest

[16:56:12.057] INFO (1): Access mode: READ_ONLY
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: std::bad_alloc]

Node.js v20.12.2
```

same for Docker on Ubuntu
```bash
docker run -p 8000:8000 -v ./kuzu:/database --rm kuzudb/explorer:latest
[17:28:35.509] INFO (1): Access mode: READ_WRITE
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: std::bad_alloc]

Node.js v20.12.2
```

same issue on podman with the recommended 

```bash
podman run -p 8000:8000 \
           -v  /home/fils/src/Projects/NIAID/domainAssessment/sof/kuzu:/database \
           --userns=keep-id \
           --rm kuzudb/explorer:latest
```

**Comment by mewim** [comment]
Hi @fils, the error seems to suggest that the database file is corrupted / not compatible with this version of Explorer. Does launching Explorer without mounting a local database works for you?

**Comment by mewim** [comment]
@fils If you are using a dev build, you can also try to use the dev version of explorer by replacing `kuzudb/explorer:latest` with `kuzudb/explorer:dev`. For dev builds, it maybe a bit tricky to align the version of explorer and the version of dev build since we do not check automatically and only keep one latest dev build for the explorer app.

**Comment by fils** [comment]
@mewim So it works now in docker via an Ubuntu VM running on my Fedora WS.   However, I am still seeing an permission issue with the lock file on podman in Fedora itself.   I can't work on this here now, but I will investigate and report back.

Thanks for your help!   Have it working in docker at least.  The people I want to share with will be using docker, not podman, so hopefully all is good now that the db versions are aligned.

Will update with what I find out re: podman

**Comment by mewim** [comment]
@fils Glad to hear it works for you in Docker. For podman, it seems that `--userns=keep-id` did the trick for me when I tested it a few months ago. If it does not work now, I'll look into it again.

**Comment by mewim** [comment]
I am closing this for now. If you encounter another issue while using Explorer, feel free to reopen this or file a new issue.
