### ISSUE TITLE
Error on starting demo

### ISSUE THREAD

**Issue by DorKeinath** [kuzudb/explorer#140]
On

```
docker run -p 8000:8000 \
           -v /absolute/path/to/database:/database \
           -e KUZU_BUFFER_POOL_SIZE=1073741824 \
           --rm kuzudb/explorer:latest
```

I get

```
INFO (1): Access mode: READ_WRITE
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: Cannot open file /database/.lock: Permission denied]

Node.js v20.12.2
```

**Comment by mewim** [comment]
Hi @DorKeinath,

It seems there is an issue accessing the database files. Have you replaced `/absolute/path/to/database` to your local database directory and do you have readwrite access to the database directory? Alternatively, you can start it with an empty database by omitting `-v /absolute/path/to/database:/database \`

**Comment by DorKeinath** [comment]
No. Sorry, greenhorn mistake. Than you!
