### ISSUE TITLE
Version compatibility <kuzu database storage version>

### ISSUE THREAD

**Issue by engapa** [kuzudb/explorer#147]
Today I tries to use explorer with a database created with kuzu_0.4.1 in python, but sadly I got this error starting the explorer:

`
[Error: Runtime exception: Trying to read a database file with a different version. Database file version: 27, Current build storage version: 26]
`

**Comment by mewim** [comment]
Hi @engapa, it seems that you are using an older version of Explorer, can you try to pull the latest version with `docker pull kuzudb/explorer:latest`?

**Comment by engapa** [comment]
yep, my mistake
using wrong commitish ....

Could you use tags and releases in this repo to map both projects ?

**Comment by mewim** [comment]
We do have version tags for Explorer: https://hub.docker.com/r/kuzudb/explorer/tags

So you could do something like `docker run -p 8000:8000 --rm kuzudb/explorer:0.4.1 `.
