### ISSUE TITLE
Kuzu Explorer only updates data after restarting docker

### ISSUE THREAD

**Issue by alew3** [kuzudb/explorer#154]
I'm on a Mac, running Kuzu Explorer via docker. 
I'm making inserts / deletes on the db via jupyter notebook outside the docker. 

I need to restart the docker to see changes reflect on the data within Kuzu Explorer.  It never updates on the same docker session.

**Comment by mewim** [comment]
This is a know issue (see #69).

**Comment by alew3** [comment]
A quickfix if realtime db updates are not so simple would be to add a refresh data button from the UI.

**Comment by mewim** [comment]
<img width="1336" alt="Screenshot 2024-07-08 at 11 18 49 PM" src="https://github.com/kuzudb/explorer/assets/14037726/13828026-ec0a-44c9-8c25-ee32a1d9c7b4">
I have implemented the button to reset the database connection in settings.

**Comment by alew3** [comment]
Just tested and it is working perfectly!

**Comment by mewim** [comment]
Closing this for now. If we figured out a way to handle this in the kernel without requiring manual resetting, I will let you know. Further discussions about this issue can continue in #69.
