### ISSUE TITLE
Enable dynamic force-directed layouts in schema view

### ISSUE THREAD

**Issue by prrao87** [kuzudb/explorer#173]
When viewing a large schema with a lot of nodes/rels, the static schema view as we have currently is rather ugly - it doesn't respond to the user moving nodes around, and takes a lot of manual effort to show everything cleanly. 

![kuzudb_schema](https://github.com/user-attachments/assets/637e847d-8c88-45f6-840c-a9ea0b6e0ccf)

It would be much nicer if the schema view also responded dynamically when the user moves nodes around, recalculating the layouts using a force-directed algorithm (same as the query editor tab).

**Comment by hamzakammar** [comment]
There's a couple issues that I've seen when trying to expirement with this. If we keep the layout type at comboForce, then the nodes movement is stiff, and they don't stay in their new positions. However, if we switch the layout type to force, the nodes move freely with force-directed layouts, but RDF graphs overlap with the rel and node graphs, which is not ideal.

**Comment by prrao87** [comment]
@mewim I don't think this is completed - tried clearing my docker cache and re-downloading the latest version, and it's still static layout in the schema view. I'm using 0.6.0.

**Comment by mewim** [comment]
Hmmm... it seems to work for me

https://github.com/user-attachments/assets/440e0f8c-8e28-4ea7-9ddf-caecaa5b960c

**Comment by prrao87** [comment]
How do I ensure I start with a clean Docker cache and download this? I can do it in 0.6.0 right? Not just dev?

**Comment by mewim** [comment]
You can do `docker system prune -a`. This feature should be available on both stable and dev versions.
