### ISSUE TITLE
Failed Relationship import removes uploaded file

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/explorer#183]
I am on the dev version of Explorer as of reporting this bug.

I uploaded a csv file (livejournal.csv). Then created a node table and a relationship table. Then I went to Import Data and prepared to import livejournal.csv and clicked "Start Import" So I see this.
<img width="1792" alt="Screen Shot 2024-08-13 at 10 59 22 PM" src="https://github.com/user-attachments/assets/9abd73a0-02fd-46f6-ab99-88d1c5efa18a">

The file apparently had an error. So it gives me this message in this window. 
<img width="1140" alt="Screen Shot 2024-08-13 at 10 59 50 PM" src="https://github.com/user-attachments/assets/a451b997-f344-48d0-a8ab-c9b497cd85a2">

When I click "Close", the uploaded file seem lost. I get to the following page.

<img width="1686" alt="Screen Shot 2024-08-13 at 11 00 07 PM" src="https://github.com/user-attachments/assets/04f9cfd4-da28-4ec9-972e-dd9c1a7fd62d">

If I instead click on somewhere else on the behind screen, I go back to the import view and livejournal.csv is still there (so as in the image before I clicked "Start Import".

**Comment by mewim** [comment]
Can you provide the full dataset?
