### ISSUE TITLE
Autofill fields when there is only one possible option/Disable fields when there is no option

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/explorer#189]
In several scenarios I noticed that in the UI there is a single possible option but the dropdowns are not auto-filled. 2 cases I ran into are:
1) When there is a single node table and we create a new rel table in the Schema view, we can autofill the From and To dropdowns.
<img width="1392" alt="Screen Shot 2024-08-14 at 12 41 02 AM" src="https://github.com/user-attachments/assets/8290ab07-df56-4cc5-be0f-fe3737ba6e71">

2) When importing a csv/parquet file to a relationship table, on the "file selection" panel, you select "Type" as "Relationship". Then in the file upload panel if you select "Use existing table", then it can autofill the table name if there is a single relationship table (same for importing to a single node table). 

<img width="1698" alt="Screen Shot 2024-08-14 at 12 41 49 AM" src="https://github.com/user-attachments/assets/660dc970-417e-466f-a8b6-5710416cc799">

Similarly when there is no option to take certain actions, we should disable those options. For example, if a db does not have a relationship table, you can still select "Relationship" under "Type" in a selected file. There are probably other cases like this but it would be good to stick to these principles when we can.

**Comment by mewim** [comment]
I do not think this is a good design. I think even if there is only one option, the user should still review and select manually. Especially in the import UI. Maybe the user has multiple files but forgot to select type for some of them. This can lead to successful, but unexpected import.

**Comment by semihsalihoglu-uw** [comment]
Hmm, I thought in my simple cases, since there is no other option auto-filling is safe but sure. I'm closing the option for now, if others independently open a similar issue, we can take that as evidence that autofilling such cases is a good idea.
