### ISSUE TITLE
Importing a CSV into an existing table without a header fails

### ISSUE THREAD

**Issue by benjaminwinger** [kuzudb/explorer#197]
E.g. importing tinysnb (`vPerson2.csv`), starting by creating the schema using the shell.
It just complains that each column is missing the column name (e.g. `Column 0 in table person is missing column name`).

And for files with a header (e.g. `vPerson.csv`) the header appears to need to match the case of the properties, unlike copying from the command line.

**Comment by mewim** [comment]
I think in both cases, if you set the column names manually from the dropdown, it will still works, but the default settings does not setup all the fields automatically (as shown below).

<img width="2429" alt="Screenshot 2024-08-14 at 10 29 29 PM" src="https://github.com/user-attachments/assets/d06b19e1-97d4-4bb4-bb7b-65427bd07d76">

For case 2, I think it is reasonable to make the UI case insensitive similar to the shell, I implmented this change in #200. However, for case 1, I do not think it is safe to assume that the column order in the file is the same as the table. I would prefer that the user always review and select manually in this case to avoid unexpected behavior.

**Comment by mewim** [comment]
Also, it seems that the dropdown for column configurations is not obvious. I am not sure if we should just expand everything by default? @semihsalihoglu-uw or @prrao87 can comment.
