### ISSUE TITLE
Data Import Suggestions

### ISSUE THREAD

**Issue by yiyun-sj** [kuzudb/explorer#201]
- [x] Having drag and drop support for adding more files (after the initial uploaded file) would be nice
- [x] If possible, can we hide the scrollbars in the import UI if they are not necessary, found them a little distracting
- [x] For rel table, my first intuition was to turn "Import to Table?" off for columns that are used as keys since importing to table suggests it is added as a column, so I wonder if import to table and use as key should be mutually exclusive

**Comment by yiyun-sj** [comment]
![image](https://github.com/user-attachments/assets/df58913f-8dd3-4479-a9ef-df5b51dc972a)
Screenshot for the scrollbar

**Comment by mewim** [comment]
Fixed in #206
