### ISSUE TITLE
Data Import Bug

### ISSUE THREAD

**Issue by mxwli** [kuzudb/explorer#202]
I have the following node tables
![image](https://github.com/user-attachments/assets/cff17df9-bfff-4f08-bcbb-2186342f80df)
And I have this relation from Post to Place
![image](https://github.com/user-attachments/assets/649648d2-8e88-4127-814d-f6a8a1e934be)
If I remove the first node table; forum, then every other node table is "shifted down by one". This causes problems with the rel table, where the TO and FROM tables are now
![image](https://github.com/user-attachments/assets/e6fba9a4-7601-450a-9ce4-170bbc1d0caa)

**Comment by mewim** [comment]
Should be fixed by #208
