### ISSUE TITLE
Cannot Import Exported Parquet Database

### ISSUE THREAD

**Issue by mxwli** [kuzudb/explorer#203]
When a database is exported, all column names are prefixed by `a.`. A property labeled `id` is now `a.id` inside the parquet file. This is a problem because the explorer then cannot recognise the dataset if you try loading it:
![image](https://github.com/user-attachments/assets/58f5289b-c00a-4ac9-8534-73a7fe4e2871)
Probably the best solution would be for the core to support syntax like the following:
```
COPY table TO 'output.csv'
```
This is a known problem, and would solve issues with importing exported data elsewhere as well.
Supporting `a.` prefixes solves this issue as well.

**Comment by mewim** [comment]
Fixed in #207
