### ISSUE TITLE
Force-refresh browser upon clicking the schema tab

### ISSUE THREAD

**Issue by prrao87** [kuzudb/explorer#209]
When using the new import feature, once the imports are successful, it's a common step to head over to the schema tab to see the resulting graph's schema. This shows an empty schema, if the user began with an empty database. The user has to manually refresh the browser page (Ctrl + R, or similar) to see the freshly updated schema. Users who are new to Kùzu may not know this, so I was thinking it makes sense to force-refresh the browser when the schema tab button is clicked. This shouldn't be an issue in terms of performance, as the schema is lightweight to load, and has a finite number of nodes/edges to render.

Also, related to #173, the schema would look a lot nicer if it also had a force-directed layout. Currently, it's static, and a lot of the nodes overlap each other when you have > 5 node or rel tables, making it look ugly upon first load.

**Comment by mewim** [comment]
Handled in #211
