### ISSUE TITLE
Force-directed layout algorithm generates more cluttered and messy visualizations

### ISSUE THREAD

**Issue by prrao87** [kuzudb/explorer#216]
## Kùzu version
0.6.0

## Operating System
macOS Sonoma 14.5

## Browser
Google Chrome: Version 127.0.6533.120 (Official Build) (arm64)

## Description

In 0.6.0, the force-directed layout seems messier than before. The edges cross over each other and the initial layout that's rendered in the graph view looks more cluttered and harder to interpret.

![force-directed-new](https://github.com/user-attachments/assets/206512b7-fd0c-47e7-8374-499d8e5717ff)

This is even worse when we visualize larger graphs. There are a lot of criss-crossing edges.
![force-directed-new-curved-edges](https://github.com/user-attachments/assets/e6a99a82-a5eb-45d9-b740-92844aaa1f69)

This wasn't happening in earlier versions. See an earlier example of a clean force-directed layout, where the edges don't appear criss-crossed on top of each other:
![force-directed-old](https://github.com/user-attachments/assets/2c83c961-7fce-401d-bc05-e53f22f03cc7)

Is this happening because we aren't running enough iterations for the force-directed algorithm to converge to a better layout?

## Steps to reproduce

The graph used to reproduce can be obtained from the attachment in #215.

The following query can be run to test:

```cypher
// Find all possible paths in an undirected manner between George and Edward with a maximum length of 5
MATCH (p1:Person)-[r*1..5]-(p2:Person)
WHERE p1.name = "George" AND p2.name = "Edward"
RETURN *;
```

**Comment by mewim** [comment]
@prrao87. #225 is merged. Can you confirm if the layouting is improved when you have some time?

**Comment by mewim** [comment]
We have switched to use `force2` layout of G6 and it looks fine for most of the cases. I am closing this for now. Feel free to reopen it if there is other layouting issues.
