### ISSUE TITLE
How is source file located?

### ISSUE THREAD

**Issue by hs41-18** [kuzudb/explorer#65]
Hi. As title says I have tried putting the source .csv into the database folder but still getting an error message:

```
The evaluation of this cell failed with the following error:
Binder exception: No file found that matches the pattern: xxx.csv.
```
any thoughts on how to resolve this? 

thanks

**Comment by mewim** [comment]
Hi @hs41-18,

The `/database` directory is for mounting the database files of Kùzu (the directory created by Kùzu automatically when you create a new database) rather than raw data files you would like to work with. To make your CSV files accessible, you could mount it at `/data` instead. Also, note that you still need the prefix directory for accessing the directory you mount when loading the files. If you mount your directory as `/data`, you need to use the path `/data/xxx.csv` to access the file instead of just `xxx.csv`.

**Comment by hs41-18** [comment]
hi @mewim I guess `/data` is just an arbitrary name you are using? if not, could you please tell me where to find that folder?  I've tried putting the CSV into a subfolder, still getting an error.

**Comment by mewim** [comment]
The `/data` in the Docker container is not completely arbitrary as we create the directory and set its permissions when building the Docker image (https://github.com/kuzudb/explorer/blob/6d8e5aa361e7d81e3064827924f70d62f1a7144c/Dockerfile#L21C1-L21C1). Do you mind sharing your `docker run` command so I can have a better idea about how you mount your data files?

**Comment by hs41-18** [comment]
just this

docker run -p 8000:8000 \
           -v /absolute/path/to/database:/database \
           --rm kuzudb/explorer:latest

**Comment by mewim** [comment]
You should mount your data directory separately from your database directory. I.e.,

```
docker run -p 8000:8000
-v /absolute/path/to/database:/database
-v /absolute/path/to/directory/with/your/csvs:/data
--rm kuzudb/explorer:latest
```
Then, your csvs will be accessible under `/data` instead the Docker container.

**Comment by hs41-18** [comment]
do I need to set permissions explicitely or explorer handling it for me? 

tried mounting `/data` separately not worked, with this it didn't work either `-u $(id -u):$(id -g) \`

**Comment by mewim** [comment]
It depends on the the permission of your directory, the user you are using, and if you are using docker or Podman. What’s the error you encountered when you mount the data files separately?

**Comment by hs41-18** [comment]
I am with an admin user running docker. Got the same error as above: 
```
 The evaluation of this cell failed with the following error:
Binder exception: No file found that matches the pattern: xxx.csv.
```

**Comment by mewim** [comment]
Can you do this to help troubleshooting? After you start the container, first run `docker ps` to get the container id, then run `docker exec -it container-id /bin/bash` to get shell access. In the shell, run `cd /data` and `ls -al` to check if your files present and have the correct permission?

**Comment by mewim** [comment]
Also, from the error message, it seems you used `data/xxx.csv`, but it should be `/data/xxx.csv` with slash at the beginning.

**Comment by hs41-18** [comment]
> Also, from the error message, it seems you used `data/xxx.csv`, but it should be `/data/xxx.csv` with slash at the beginning.

yes indeed, that was the stupid mistake :) I can see the data files from container files and have access

**Comment by NeuralFlux** [comment]
> Hi [@hs41-18](https://github.com/hs41-18),
> 
> The `/database` directory is for mounting the database files of Kùzu (the directory created by Kùzu automatically when you create a new database) rather than raw data files you would like to work with. To make your CSV files accessible, you could mount it at `/data` instead. Also, note that you still need the prefix directory for accessing the directory you mount when loading the files. If you mount your directory as `/data`, you need to use the path `/data/xxx.csv` to access the file instead of just `xxx.csv`.

Hi @hs41-18 ,
Is this a standard practice in Docker? I spent quite some time debugging why the data files could not be read. Perhaps it will be helpful to add your comment to the docs [here](https://docs.kuzudb.com/visualization/#buffer-pool-size).
