### ISSUE TITLE
Provide means to set default node property as some other property than primary key

### ISSUE THREAD

**Issue by prrao87** [kuzudb/explorer#68]
It would be great if we could preset the node properties displayed (it defaults to picking the primary key) - instead, if the user knew what they wanted to display on the node, say `name` or some other property, that would make the graph displayed a lot more readable and useful. Primary key on many occasions is an integer or uuid, so it's pretty ugly or not useful when displayed.

Is there a way to provide this as a config file or similar to the Dockerfile before we run the display server?

![image](https://github.com/kuzudb/explorer/assets/35005448/88d3272f-da6a-45e8-8040-35fab390433a)

This is an example of a transaction graph that has integer primary keys for the nodes - the initial graph displayed is not very useful and I invariably end up having to customize the node display settings every time I load the explorer.

**Comment by mewim** [comment]
So the feature request is for a way to persist the customization? Maybe we can try to persist to the database file itself?

**Comment by prrao87** [comment]
How can this be addressed at the database level? It's a visual option at the JavaScript level, I think?

**Comment by mewim** [comment]
One potential solution is to save this information into a internal table (maybe a table like with `__explorer_config__`) and write the settings to the database itself. Then next time the database is opened via the explorer, the config is read and sent to the frontend.

**Comment by prrao87** [comment]
Hmm, are you suggesting this because we also have to think about when we embed the explorer into a standalone application? Because then, having a config file for Docker may not work.

Neo4j browser does this using a [GraSS](https://neo4j.com/docs/browser-manual/current/operations/browser-styling/#grass) file - can we take some ideas from that?

**Comment by mewim** [comment]
Yeah we can do that as well. I was suggesting saving the config to the database because I think it would probably be the easiest for the user. They just need to load the database as-is and it will automatically reload the viz configuration for them. Having a separate config file may incur an additional overhead of manually managing and loading them.

**Comment by prrao87** [comment]
Sure, whatever interface you think would be easy enough to implement, we can test and see how the feedback is. There's plenty of room for iteration later on!
