### ISSUE TITLE
Default configuration for _rt and _lt relationship tables is Table name, not iri

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/explorer#78]
I ran the below query and this is the visualization I got. We should show the iri as we had decided.

<img width="1596" alt="Screen Shot 2024-02-09 at 5 10 05 PM" src="https://github.com/kuzudb/explorer/assets/26987866/7c293ae7-2b8e-4217-b2f2-a9ad22c5131e">

**Comment by mewim** [comment]
Did you pull the latest version from Docker Hub? I think this has been addressed.

**Comment by mewim** [comment]
OK. Then this may be a bug

**Comment by mewim** [comment]
@semihsalihoglu-uw I checked again and still cannot reproduce the bug. Could you please send me the database files that causes the issue?

**Comment by semihsalihoglu-uw** [comment]
OK, I cannot reproduce this now. Not sure what happened. Closing this.
