### ISSUE TITLE
Open the side panel when clicking on a node or edge. Expand a node to its neighbors when double clicking.

### ISSUE THREAD

**Issue by semihsalihoglu-uw** [kuzudb/explorer#79]
Currently the side panel of the graph view in the shell panel does not open automatically. One has to click on the arrow at the end of the  graph view to open it and see the node and relationship properties. I think it should open as one clicks on a node/rel. 

We should also have the behavior that when double clicking on a node, it should expand to its neighbors.

- [x] Open the side panel when clicking on a node or edge
- [x] Expand a node to its neighbors when double clicking

**Comment by mewim** [comment]
1 is addressed in #82
